### ISSUE TITLE
Initializing in an existing case management environment

### ISSUE THREAD

**Issue by gmercede** [Acumatica/PX.AutomatedCaseReminder.KB.Ext#1]
If Acumatica case management system has existing cases that are Customer Pending, how can they be reset?  Meaning you would not want to bombard case contact recipients with tons of emails.  Instead a reset to ensure the timer can start over.

We notice the last activity age is calculated based on the corresponding CRActivity table MAX LastmodifiedDAteTime for all outgoing type activities.  Resetting that to today might be an option, but is that a decent option and/or is there anything better that does not involve overwriting the correct last modified date for an activity

**Comment by DhirenChhapgar** [comment]
There’s no need to update the `LastModifiedDateTime` of last Case Activity.

Determination of Case to be included or not in reminder process is based on `CRCaseExt.UsrReminderCount` and `CRCase.LastActivityAge`. 

![image](https://user-images.githubusercontent.com/5994708/30187131-5ae042e6-93f6-11e7-9606-2f24964ba601.png)

You can implement your own un-bound user field (`UsrLastActivityAge` for example) in extension of `CRCase` and use that for comparison in view delegate instead of out-of-box `CRCase.LastActivityAge`. You can utilize `PXFormula` attribute for `UsrLastActivityAge` and manipulate value as per your need.

Other approach would be to add additional filters on Case creation date for `AutoRemindCaseInfo` Projection DAC to exclude very old cases.
